name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: "^3.0.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter

  # dash: ^1.0.3
  dash:
    path: ../../dash/
  rxdart: ^0.26.0
  cupertino_icons: ^1.0.2

dependency_overrides:
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.6.1
  # dash_generator: ^1.0.3
  dash_generator:
    path: ../../dash_generator/


flutter:
  uses-material-design: true
