name: dash_generator
author: Vinicius Sossella <viniciussossella@gmail.com>
description: Dash Generator library is responsible to generate all the boilerplate code needed by dash library.
version: 0.5.7
homepage: https://github.com/ViniciusSossela/dash

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: ^1.2.2
  source_gen: ^0.9.4+6
  code_builder: ^3.2.1
  dash: ^0.5.6
  built_collection: ^4.3.0
  dart_style: ^1.3.3

dev_dependencies:
  build_runner: ^1.7.2
  pedantic: ^1.8.0+1
  flutter_test:
      sdk: flutter