name: dash_generator
description: Dash Generator library is responsible to generate all the boilerplate code needed by dash library.
version: 1.0.1
homepage: https://github.com/ViniciusSossela/dash

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  build: ^1.5.2
  source_gen: ^0.9.6
  analyzer: ^0.41.2
  code_builder: ^3.7.0
  dash: ^1.0.1
  # dash:
  #   path: ../dash/
  built_collection: ^5.0.0
  dart_style: ^1.3.10

dev_dependencies:
  build_runner: ^1.10.12
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter