name: dash_generator
description: Dash Generator library is responsible to generate all the boilerplate code needed by dash library.
version: 0.3.0
author: Vinícius Sossella <viniciussossella@gmail.com>
homepage: https://github.com/ViniciusSossela/dash

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: ^1.1.0
  source_gen: ^0.9.4
  code_builder: ^3.1.3
  dash: ^0.3.0

dev_dependencies:
  build_test: ^0.10.0
  build_runner: ^1.1.3
