name: dash_generator
description: Dash Generator library is responsible to generate all the boilerplate code needed by dash library.
version: 1.0.0-nullsafety.0
homepage: https://github.com/ViniciusSossela/dash

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  build: ^1.2.2
  source_gen: ^0.9.4+6
  code_builder: ^3.5.0
  dash: ^1.0.0-nullsafety.0
  # dash:
  #   path: ../dash/
  built_collection: ^4.3.2
  dart_style: ^1.3.3
  analyzer: ^0.40.4

dev_dependencies:
  build_runner: ^1.10.12
  pedantic: ^1.10.0-nullsafety.3  
  flutter_test:
    sdk: flutter