name: dash_generator
description: Dash Generator library is responsible to generate all the boilerplate code needed by dash library.
version: 1.0.8
homepage: https://github.com/ViniciusSossela/dash

environment:
  sdk: "^3.0.0"

dependencies:
  build: ^3.0.1
  source_gen: ^3.1.0
  code_builder: ^4.1.0
  dash:
    path: ../dash/
  built_collection: ^5.0.0
  analyzer: ^7.5.5

dependency_overrides:
  meta: ^1.17.0

dev_dependencies:
  build_runner: ^2.6.1
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
