name: dash_generator
description: Dash Generator library is responsible to generate all the boilerplate code needed by dash library.
version: 0.5.3
author: Vinícius Sossella <viniciussossella@gmail.com>
homepage: https://github.com/ViniciusSossela/dash

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: ^1.1.1
  source_gen: ^0.9.4
  code_builder: ^3.1.3
  dash: ^0.5.3
  test: ^1.0.0
  analyzer: ^0.35.0
  built_collection: ^4.1.0
  dart_style: ^1.2.4

dev_dependencies:
  build_runner: ^1.2.8
  pedantic: '1.4.0'
