name: dash_generator
description: Dash Generator library is responsible to generate all the boilerplate code needed by dash library.
version: 1.0.7
homepage: https://github.com/ViniciusSossela/dash

environment:
  sdk: "^3.0.0"

dependencies:
  build: ^2.1.1
  source_gen: ^2.0.0
  code_builder: ^4.1.0
  dash: ^1.0.4
  analyzer: ^6.9.0
  # dash:
  #   path: ../dash/
  built_collection: ^5.0.0
  dart_style: ^2.0.1

dev_dependencies:
  build_runner: ^2.0.3
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
