name: dash
description: Dash library is responsible to offer a BlocProvider pattern that cares about dispose all the streams of blocs.
version: 0.4.0
author: Vinícius Sossella <viniciussossella@gmail.com>
homepage: https://github.com/ViniciusSossela/dash

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.0.0